### ISSUE TITLE
Add candidates to the contests in the EDF

### ISSUE THREAD

**Issue by cwulfman** [ion-oset/cast-vote-records#10]
[`CandidateSelection`s](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.1500-100r2.pdf#%5B%7B%22num%22%3A146%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C70%2C720%2C0%5D) are missing from both JSON and XML versions.

**Comment by ion-oset** [comment]
I've added these to the JSON. I'll leave these to you to do the XML since you have better validation set up than I do.

Note that I [reconciled IDs](https://github.com/ion-oset/cast-vote-records/pull/5/commits/57ea9840d3d37663bcaa7a30a3c2a8ee91a9a038) that were out of sync between the CVR and EDF, and fixed a wrongly spelled candidate name so some names have changed.
