### ISSUE TITLE
CVR files: should be one per ballot

### ISSUE THREAD

**Issue by cwulfman** [ion-oset/cast-vote-records#11]
jetsons_main_cvr.json contains snapshots for different voters's ballots from different districts. We need 4 cvr files , each repesenting the cast votes of a different voter, one in each of our 4 precincts:

bedrock precinct
downtown precinct
port precinct
spacetown precinct

So maybe

precinct_bedrock_cvr.xml/json
precinct_downtown_cvr.xml/json
precinct_port_cvr.xml/json
precinct_spacetown_cvr.xml/json

**Comment by ion-oset** [comment]
I'd do this: `jetsons_<name>-precinct_cvr.<filetype>`.
I want to keep the "jetsons" prefix because there are other samples in the repository.

Making these files is easy enough: take the unified files and copy them four times and delete the unneeded entries. It also means that we have a lot of duplication so they are better generated than hand-maintained. Does it make sense to generate them via XSLT / JQ? This is trivial JQ, I assume it's trivial XSLT too. We'd still check in the final results so they are immediately accessible, but we'd only have to maintain one source file.

**Comment by cwulfman** [comment]
You’re reading my mind, Ion — I’m working on the XSLT as I write this.

On Jun 11, 2021, at 6:21 PM, ion-oset ***@***.******@***.***>> wrote:



I'd do this: jetsons_<name>-precinct_cvr.<filetype>.
I want to keep the "jetsons" prefix because there are other samples in the repository.

Making these files is easy enough: take the unified files and copy them four times and delete the unneeded entries. It also means that we have a lot of duplication so they are better generated than hand-maintained. Does it make sense to generate them via XSLT / JQ? This is trivial JQ, I assume it's trivial XSLT too. We'd still check in the final results so they are immediately accessible, but we'd only have to maintain one source file.

**Comment by ion-oset** [comment]
Excellent. I'll work on the JQ.

**Comment by cwulfman** [comment]
These things are actually rather tricky.  For purposes of the mock-up, I don't think it matters much, as long as the current snapshot indicates the right things to be printed out by the mobile app (we're unfolding the lotus flower only to refold it so that it can be unfolded again). I'll add to the xml PR to show you what I'm thinking.

See https://github.com/ion-oset/cast-vote-records/pull/12

**Comment by cwulfman** [comment]
references issue #4

**Comment by ion-oset** [comment]
The changes were made manually and are closed on the [`jetsons`](https://github.com/ion-oset/cast-vote-records/tree/jetsons) branch as of d744a0ee. The scripting has been deferred to #15.
